### Numpy

In [1]:
# sort , search & Counting functions 

In [2]:
import numpy as np 

In [9]:
arr = np.array([2,3,8,9,10,5,6])

In [10]:
arr

array([ 2,  3,  8,  9, 10,  5,  6])

In [11]:
np.sort(arr)

array([ 2,  3,  5,  6,  8,  9, 10])

In [12]:
np.searchsorted(arr,4)

2

In [13]:
np.searchsorted(arr,11)

7

In [14]:
np.searchsorted(arr,1)

0

In [16]:
arr1 = np.array([0,324,325,862,458,0,0,0,0,234])

In [17]:
arr1

array([  0, 324, 325, 862, 458,   0,   0,   0,   0, 234])

In [18]:
np.count_nonzero(arr1)

5

In [19]:
np.where(arr1 > 0)

(array([1, 2, 3, 4, 9]),)

In [22]:
np.extract(arr1 > 2,arr1)

array([324, 325, 862, 458, 234])

In [23]:
# Numpy -> Byte swapping

In [24]:
arr1 

array([  0, 324, 325, 862, 458,   0,   0,   0,   0, 234])

In [25]:
arr.byteswap()

array([144115188075855872, 216172782113783808, 576460752303423488,
       648518346341351424, 720575940379279360, 360287970189639680,
       432345564227567616])

In [26]:
arr

array([ 2,  3,  8,  9, 10,  5,  6])

In [27]:
arr1.byteswap()

array([                   0,  4900197869555810304,  4972255463593738240,
        6774258264495357952, -3890828603071397888,                    0,
                          0,                    0,                    0,
       -1585267068834414592])

In [28]:
# Numpy -> Copies & views

In [29]:
arr1

array([  0, 324, 325, 862, 458,   0,   0,   0,   0, 234])

In [31]:
a = np.copy(arr1)
# a is an deep copy 

In [32]:
a

array([  0, 324, 325, 862, 458,   0,   0,   0,   0, 234])

In [33]:
b= arr1.view()

In [34]:
b

array([  0, 324, 325, 862, 458,   0,   0,   0,   0, 234])

In [35]:
b[0] = 234

In [36]:
b

array([234, 324, 325, 862, 458,   0,   0,   0,   0, 234])

In [37]:
arr1

array([234, 324, 325, 862, 458,   0,   0,   0,   0, 234])

In [38]:
# Numpy -> Matrix library

In [39]:
import numpy.matlib as nm

In [40]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [42]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [43]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [44]:
# Numpy -> Linear Algebra 

In [45]:
arr1

array([234, 324, 325, 862, 458,   0,   0,   0,   0, 234])

In [54]:
arr1 = np.random.randint([[2,3],[4,5]])
arr2 = np.random.randint([[5,3],[2,5]])

In [55]:
arr1

array([[0, 0],
       [2, 1]])

In [50]:
arr2

array([[3, 2],
       [0, 3]])

In [56]:
np.dot(arr1,arr2)

array([[0, 0],
       [5, 4]])

In [57]:
arr1@arr2

array([[0, 0],
       [5, 4]])