### Numpy

In [1]:
import numpy as np 

In [2]:
# numpy -> array manipulation

In [4]:
np.random.randint(1,10,(4,4))

array([[3, 2, 9, 8],
       [5, 3, 8, 9],
       [2, 4, 2, 1],
       [8, 9, 3, 3]])

In [5]:
arr = np.random.randint(1,10,(4,4))

In [6]:
arr.reshape(8,2)

array([[9, 3],
       [9, 9],
       [1, 6],
       [2, 9],
       [5, 4],
       [3, 7],
       [7, 6],
       [3, 3]])

In [7]:
arr

array([[9, 3, 9, 9],
       [1, 6, 2, 9],
       [5, 4, 3, 7],
       [7, 6, 3, 3]])

In [8]:
arr.T

array([[9, 1, 5, 7],
       [3, 6, 4, 6],
       [9, 2, 3, 3],
       [9, 9, 7, 3]])

In [9]:
arr.flatten()

array([9, 3, 9, 9, 1, 6, 2, 9, 5, 4, 3, 7, 7, 6, 3, 3])

In [10]:
arr

array([[9, 3, 9, 9],
       [1, 6, 2, 9],
       [5, 4, 3, 7],
       [7, 6, 3, 3]])

In [11]:
np.expand_dims(arr,axis = 1)

array([[[9, 3, 9, 9]],

       [[1, 6, 2, 9]],

       [[5, 4, 3, 7]],

       [[7, 6, 3, 3]]])

In [12]:
np.expand_dims(arr,axis=0)

array([[[9, 3, 9, 9],
        [1, 6, 2, 9],
        [5, 4, 3, 7],
        [7, 6, 3, 3]]])

In [13]:
data = np.array([[1],[2],[3]])

In [14]:
np.squeeze(data)

array([1, 2, 3])

In [17]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [18]:
np.roll(data,3)

array([[1],
       [2],
       [3]])

In [19]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [20]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [21]:
# numpy -> Binary operation

In [24]:
arr1 = np.random.randint(1,10, (3,4))
arr2 = np.random.randint(1,10, (3,4))

In [26]:
arr1

array([[9, 9, 7, 9],
       [1, 7, 8, 7],
       [1, 8, 7, 3]])

In [27]:
arr2

array([[4, 2, 7, 6],
       [3, 3, 4, 8],
       [6, 8, 2, 9]])

In [29]:
arr1 +arr2
# index wise summation operation

array([[13, 11, 14, 15],
       [ 4, 10, 12, 15],
       [ 7, 16,  9, 12]])

In [30]:
arr1 * arr2

array([[36, 18, 49, 54],
       [ 3, 21, 32, 56],
       [ 6, 64, 14, 27]])

In [31]:
arr1 /arr2

array([[2.25      , 4.5       , 1.        , 1.5       ],
       [0.33333333, 2.33333333, 2.        , 0.875     ],
       [0.16666667, 1.        , 3.5       , 0.33333333]])

In [32]:
arr1 - arr2

array([[ 5,  7,  0,  3],
       [-2,  4,  4, -1],
       [-5,  0,  5, -6]])

In [33]:
arr1 ** arr2

array([[    6561,       81,   823543,   531441],
       [       1,      343,     4096,  5764801],
       [       1, 16777216,       49,    19683]])

In [34]:
-arr1

array([[-9, -9, -7, -9],
       [-1, -7, -8, -7],
       [-1, -8, -7, -3]])

In [35]:
arr1

array([[9, 9, 7, 9],
       [1, 7, 8, 7],
       [1, 8, 7, 3]])

In [36]:
arr1 >arr2

array([[ True,  True, False,  True],
       [False,  True,  True, False],
       [False, False,  True, False]])

In [37]:
# Numpy -> string operation

In [38]:
arr = np.array(["sudh","kumar"])

In [39]:
arr

array(['sudh', 'kumar'], dtype='<U5')

In [40]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [41]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [42]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [43]:
# Numpy -> Mathematical Functions

In [44]:
arr1

array([[9, 9, 7, 9],
       [1, 7, 8, 7],
       [1, 8, 7, 3]])

In [46]:
np.sin(arr1)

array([[0.41211849, 0.41211849, 0.6569866 , 0.41211849],
       [0.84147098, 0.6569866 , 0.98935825, 0.6569866 ],
       [0.84147098, 0.98935825, 0.6569866 , 0.14112001]])

In [47]:
np.cos(arr1)

array([[-0.91113026, -0.91113026,  0.75390225, -0.91113026],
       [ 0.54030231,  0.75390225, -0.14550003,  0.75390225],
       [ 0.54030231, -0.14550003,  0.75390225, -0.9899925 ]])

In [48]:
np.tan(arr1)

array([[-0.45231566, -0.45231566,  0.87144798, -0.45231566],
       [ 1.55740772,  0.87144798, -6.79971146,  0.87144798],
       [ 1.55740772, -6.79971146,  0.87144798, -0.14254654]])

In [49]:
np.log10(arr1)

array([[0.95424251, 0.95424251, 0.84509804, 0.95424251],
       [0.        , 0.84509804, 0.90308999, 0.84509804],
       [0.        , 0.90308999, 0.84509804, 0.47712125]])

In [50]:
np.exp(arr1)

array([[8.10308393e+03, 8.10308393e+03, 1.09663316e+03, 8.10308393e+03],
       [2.71828183e+00, 1.09663316e+03, 2.98095799e+03, 1.09663316e+03],
       [2.71828183e+00, 2.98095799e+03, 1.09663316e+03, 2.00855369e+01]])

In [52]:
np.power(arr1,3)

array([[729, 729, 343, 729],
       [  1, 343, 512, 343],
       [  1, 512, 343,  27]])

In [53]:
np.mean(arr1)

6.333333333333333

In [55]:
np.median(arr1)

7.0

In [57]:
np.std(arr1)

2.8382310609877335

In [58]:
np.var(arr1)

8.055555555555555

In [59]:
np.min(arr1)

1

In [60]:
np.max(arr1)

9

In [61]:
# Numpy -> Airthmetic operation

In [62]:
arr1

array([[9, 9, 7, 9],
       [1, 7, 8, 7],
       [1, 8, 7, 3]])

In [63]:
arr2

array([[4, 2, 7, 6],
       [3, 3, 4, 8],
       [6, 8, 2, 9]])

In [64]:
arr1 - arr2

array([[ 5,  7,  0,  3],
       [-2,  4,  4, -1],
       [-5,  0,  5, -6]])

In [65]:
np.subtract(arr1,arr2)

array([[ 5,  7,  0,  3],
       [-2,  4,  4, -1],
       [-5,  0,  5, -6]])

In [66]:
np.multiply(arr1,arr2)

array([[36, 18, 49, 54],
       [ 3, 21, 32, 56],
       [ 6, 64, 14, 27]])

In [68]:
np.mod(arr1,arr2)

array([[1, 1, 0, 3],
       [1, 1, 0, 7],
       [1, 0, 1, 3]])

In [69]:
np.power(arr1,arr2)

array([[    6561,       81,   823543,   531441],
       [       1,      343,     4096,  5764801],
       [       1, 16777216,       49,    19683]])

In [71]:
np.sqrt(arr2)

array([[2.        , 1.41421356, 2.64575131, 2.44948974],
       [1.73205081, 1.73205081, 2.        , 2.82842712],
       [2.44948974, 2.82842712, 1.41421356, 3.        ]])

In [72]:
# Numpy -> statistical functions.

In [73]:
arr1

array([[9, 9, 7, 9],
       [1, 7, 8, 7],
       [1, 8, 7, 3]])

In [74]:
np.mean(arr1)

6.333333333333333

In [75]:
np.std(arr1)

2.8382310609877335

In [76]:
np.median(arr1)

7.0