In [1]:
import numpy as np

In [2]:
range(5)

range(0, 5)

In [3]:
list(range(5))

[0, 1, 2, 3, 4]

In [4]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
list(range(0.4,10.4))

TypeError: 'float' object cannot be interpreted as an integer

In [7]:
np.arange(0.4,10.4,0.2)

array([ 0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,
        2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,
        4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,
        7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,
        9.2,  9.4,  9.6,  9.8, 10. , 10.2])

In [8]:
list(np.arange(0.4,10.4,0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [9]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [10]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [11]:
np.logspace(1,5,base = 2)

array([ 2.        ,  2.11642982,  2.2396376 ,  2.37001791,  2.50798829,
        2.65399061,  2.80849244,  2.97198858,  3.14500263,  3.32808868,
        3.52183307,  3.72685628,  3.94381489,  4.17340372,  4.41635805,
        4.67345595,  4.94552078,  5.23342383,  5.53808714,  5.8604864 ,
        6.2016541 ,  6.56268285,  6.94472885,  7.34901563,  7.77683793,
        8.22956587,  8.70864932,  9.21562258,  9.75210923, 10.31982742,
       10.92059526, 11.55633675, 12.22908788, 12.94100316, 13.69436252,
       14.49157863, 15.3352046 , 16.22794219, 17.17265042, 18.17235475,
       19.23025679, 20.3497445 , 21.53440308, 22.78802646, 24.11462942,
       25.51846045, 27.00401538, 28.57605177, 30.23960411, 32.        ])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [17]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
arr = np.ones((3,4))

In [21]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
arr + 5 

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [23]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
arr * 4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [25]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [26]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
arr1 = np.eye(5)

In [28]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
import pandas as pd 

In [30]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [31]:
np.random.rand(2,3)

array([[0.16771652, 0.45364828, 0.8055641 ],
       [0.76152926, 0.07476352, 0.63583565]])

In [32]:
np.random.randn(2,3)

array([[ 0.64818891,  1.53435006,  0.23455033],
       [-1.11093764, -0.44031654, -0.60101954]])

In [33]:
np.random.randint(1,5,(3,4))

array([[4, 4, 3, 2],
       [4, 4, 3, 1],
       [4, 1, 2, 2]])

In [34]:
arr2 = np.random.randint(1,5,(3,4))

In [35]:
arr2

array([[3, 4, 4, 4],
       [4, 3, 1, 3],
       [3, 4, 1, 3]])

In [36]:
arr.size

12

In [37]:
arr2.shape

(3, 4)

In [39]:
arr2.reshape(6,2)
# when we use reshape we can build shape only equal to old size 

array([[3, 4],
       [4, 4],
       [4, 3],
       [1, 3],
       [3, 4],
       [1, 3]])

In [40]:
arr2.reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

In [41]:
arr2.reshape(4,3)

array([[3, 4, 4],
       [4, 4, 3],
       [1, 3, 3],
       [4, 1, 3]])

In [43]:
arr2.reshape(4,-1)

array([[3, 4, 4],
       [4, 4, 3],
       [1, 3, 3],
       [4, 1, 3]])

In [44]:
arr2.reshape(6,-100325465)

array([[3, 4],
       [4, 4],
       [4, 3],
       [1, 3],
       [3, 4],
       [1, 3]])

In [45]:
arr2.reshape(2,2,3)

array([[[3, 4, 4],
        [4, 4, 3]],

       [[1, 3, 3],
        [4, 1, 3]]])

In [46]:
arr2.reshape(2,3,2,1,1,1,1)

array([[[[[[[3]]]],



         [[[[4]]]]],




        [[[[[4]]]],



         [[[[4]]]]],




        [[[[[4]]]],



         [[[[3]]]]]],





       [[[[[[1]]]],



         [[[[3]]]]],




        [[[[[3]]]],



         [[[[4]]]]],




        [[[[[1]]]],



         [[[[3]]]]]]])

In [48]:
arr1 = np.random.randint(1,10,(5,6))

In [49]:
arr1

array([[5, 9, 4, 3, 3, 2],
       [7, 8, 2, 8, 5, 9],
       [8, 3, 9, 2, 6, 1],
       [6, 9, 7, 2, 3, 6],
       [9, 7, 6, 7, 3, 3]])

In [50]:
arr1 > 8

array([[False,  True, False, False, False, False],
       [False, False, False, False, False,  True],
       [False, False,  True, False, False, False],
       [False,  True, False, False, False, False],
       [ True, False, False, False, False, False]])

In [51]:
arr1[arr1>8]

array([9, 9, 9, 9, 9])

In [52]:
arr1

array([[5, 9, 4, 3, 3, 2],
       [7, 8, 2, 8, 5, 9],
       [8, 3, 9, 2, 6, 1],
       [6, 9, 7, 2, 3, 6],
       [9, 7, 6, 7, 3, 3]])

In [55]:
arr1[0,[0,1]]

array([5, 9])

In [56]:
arr1[2:4,[2,3]]

array([[9, 2],
       [7, 2]])

In [58]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [59]:
arr1

array([[2, 2, 2],
       [2, 2, 1],
       [1, 2, 2]])

In [60]:
arr2

array([[1, 2, 2],
       [1, 2, 2],
       [1, 1, 1]])

In [61]:
arr1 + arr2

array([[3, 4, 4],
       [3, 4, 3],
       [2, 3, 3]])

In [62]:
arr1-arr2

array([[ 1,  0,  0],
       [ 1,  0, -1],
       [ 0,  1,  1]])

In [63]:
arr1*arr2

array([[2, 4, 4],
       [2, 4, 2],
       [1, 2, 2]])

In [64]:
arr1

array([[2, 2, 2],
       [2, 2, 1],
       [1, 2, 2]])

In [65]:
arr2

array([[1, 2, 2],
       [1, 2, 2],
       [1, 1, 1]])

In [66]:
# matrix multiplication

In [67]:
arr1@arr2

array([[ 6, 10, 10],
       [ 5,  9,  9],
       [ 5,  8,  8]])

In [68]:
arr1/arr2

array([[2. , 1. , 1. ],
       [2. , 1. , 0.5],
       [1. , 2. , 2. ]])

In [69]:
arr1/0

/tmp/ipykernel_2112/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [70]:
# numpy -> brodcasting

In [71]:
arr = np.zeros((3,4))

In [73]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [74]:
arr * 5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [75]:
a = np.array([1,2,3,4])

In [76]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [77]:
b = np.array([3,4,5])

In [78]:
arr + b

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [79]:
b1 = np.array([[3,4,5]])

In [81]:
arr + b1

ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [83]:
arr + b1.T
# transpose the matrix

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [84]:
b1.T

array([[3],
       [4],
       [5]])

In [85]:
arr4 =arr + b1.T

In [86]:
arr4

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [87]:
np.sqrt(arr4)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [88]:
np.log10(arr4)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [90]:
np.exp(arr4)
# exponent

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [91]:
np.mean(arr4)

4.0

np.max(arr4)