### Numpy

In [3]:
import numpy as np 

In [4]:
l =[1,2,3,4,5]

In [5]:
np.array(l)

array([1, 2, 3, 4, 5])

In [6]:
arr =np.array(l)

In [7]:
type(arr)

numpy.ndarray

In [8]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [9]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr1 =np.array([[1,2,3],[4,5,6]])

In [11]:
arr.ndim
# dimension of arr

1

In [12]:
arr1.ndim

2

In [13]:
arr

array([1, 2, 3, 4, 5])

In [14]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.matrix(l)

matrix([[1, 2, 3, 4, 5]])

In [16]:
mat =np.matrix(l)

In [17]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [18]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [19]:
arr

array([1, 2, 3, 4, 5])

In [20]:
a =arr

In [21]:
a

array([1, 2, 3, 4, 5])

In [22]:
arr

array([1, 2, 3, 4, 5])

In [23]:
arr[0] = 100

In [24]:
arr

array([100,   2,   3,   4,   5])

In [25]:
a

array([100,   2,   3,   4,   5])

In [33]:
print(id(a))
print(id(arr))

139871812301808
139871812301808


In [34]:
# both the objects has same id this copy operation is called as solo copy operation 

In [27]:
b=np.copy(arr)

In [28]:
b[0]=234

In [29]:
b

array([234,   2,   3,   4,   5])

In [30]:
arr

array([100,   2,   3,   4,   5])

In [31]:
print(id(b))
print(id(arr))

139871651049712
139871812301808


In [32]:
# the id is different that mean both ojects are different

In [35]:
np.fromfunction(lambda i,j : i ==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [36]:
np.fromfunction(lambda i,j : i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [39]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [40]:
iterable =(i*i for i in range(5))

In [41]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [42]:
np.fromstring('23 45 56',sep = ' ')

array([23., 45., 56.])

In [43]:
np.fromstring('23,45,56',sep = ',')

array([23., 45., 56.])

In [44]:
arr

array([100,   2,   3,   4,   5])

In [45]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
arr.ndim

1

In [47]:
arr1.ndim

2

In [48]:
arr.size

5

In [49]:
arr1.size

6

In [50]:
arr.shape

(5,)

In [52]:
arr1.shape
# 2 rows and 3 column

(2, 3)

In [53]:
arr.dtype

dtype('int64')

In [54]:
arr1.dtype

dtype('int64')